FROM python:3.9-slim

WORKDIR /app

# Copia tudo que é necessário
COPY requirements.txt .
COPY common/ ./common/
COPY consumer/ ./consumer/

# Instala dependências
RUN pip install --no-cache-dir -r requirements.txt

# Define o diretório de trabalho para o consumer
WORKDIR /app/consumer

# Comando para rodar
CMD ["python", "main.py"]